[tool.poetry]
name = "lesson-1"
version = "0.1.0"
description = "Homework 1 MLOps 2025"
authors = [
    {name = "Danil Krivonogov",email = "krivonogov0@vk.com"}
]

[tool.poetry.dependencies]
python = ">=3.12"
pandas = "~2.2"
scikit-learn = "~1.5"
dvc = "~3.50"
great-expectations = "~0.18"
pyyaml = "~6.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.7"
black = "25.11.0"
isort = "7.0.0"
pre-commit = "^4.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
